### ISSUE TITLE
Use of datetime.UTC is not backwards compatible (breaks in Python ≤ 3.10)

### ISSUE THREAD

**Issue by codyfletcher** [alexgolec/schwab-py#27]
**Description of Bug**

There is a call to `datetime.UTC` that fails in python 3.10, but seems to work in 3.11. 
See schwab/client/base.py", line 214, in _make_order_query:
    `datetime.datetime.now(datetime.UTC) -`

Error: `AttributeError: module 'datetime' has no attribute 'UTC'`

This causes any calls with dates to fail, even if you aren't specifying any dates (get_orders_by, get_transactions, etc).

**Solution**

I believe swapping out `datetime.UTC` with `datetime.timezone.UTC` might create a backwards compatible solution.

**Code to Reproduce**

A basic example:

Run Python 3.10 console:

```
Python 3.10.13 (main, Sep 26 2023, 10:22:02) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin

>>> import datetime
>>> datetime.UTC

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'datetime' has no attribute 'UTC'
```

**Expected Behavior**
<EXPECTED BEHAVIOR>

**Actual Behavior**
<ACTUAL BEHAVIOR>

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html

**Comment by codyfletcher** [comment]
This is fixed! 🎉
